configure_dotfiles: true
configure_terminal: false
configure_osx: true
configure_asdf: true

dotfiles_repo: https://github.com/voboshi/dotfiles-1.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
dotfiles_files:
  - .zshrc
  - .zshenv
  - .gitignore
  - .osx
  - .p10k.zsh

homebrew_installed_packages:
  - autoconf
  - automake
  - libtool
  - allure
  - asdf
  - bash
  - bat
  - exa
  - fd
  - findutils
  - fzf
  - gh
  - git-delta
  - helm
  - httpie
  - jq
  - k6
  - kubernetes-cli
  - mas
  - ripgrep
  - shellcheck
  - the_silver_searcher
  - thefuck
  - unzip
  - yq
  - zsh
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - aws/tap/aws-sam-cli
  - cloudquery/tap/cloudquery
  - common-fate/granted/granted
  - hashicorp/tap/terraform-ls
  - kreuzwerker/taps/m1-terraform-provider-helper
  - mergestat/mergestat/mergestat
  - romkatv/powerlevel10k/powerlevel10k
  - turbot/tap/steampipe
  - weaveworks/tap/eksctl
  - wix/brew/applesimutils

homebrew_taps:
  - 1password/tap
  - aws/tap
  - cloudquery/tap
  - common-fate/granted
  - hashicorp/tap
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core
  - kreuzwerker/taps
  - mergestat/mergestat
  - romkatv/powerlevel10k
  - turbot/tap
  - weaveworks/tap
  - wix/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password-cli
  - arc
  - firefox
  - font-fira-code
  - font-fira-code-nerd-font
  - font-iosevka
  - font-iosevka-nerd-font
  - font-iosevka-ss08
  - font-iosevka-ss18
  - fork
  - google-chrome
  - iterm2
  - owasp-zap
  - postman
  - visual-studio-code

mas_installed_apps:
  - { id: 1099568401, name: "Home Assistant" }
  - { id: 1568395334, name: "Collections Database" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409183694, name: "Keynote" }
  # - { id: 497799835, name: "Xcode" }
  - { id: 639968404, name: "Parcel - Delivery Tracking" }
  - { id: 1659154653, name: "Mona for Mastodon" }
  - { id: 1606897889, name: "Consent-O-Matic" }
  - { id: 1224268771, name: "Screens 4" }
  - { id: 1569813296, name: "1Password for Safari"}
  - { id: 1591303229, name: "Vinegar - Tube Cleaner" }
  - { id: 1601151613, name: "Baking Soda - Tube Cleaner" }
  - { id: 1579902068, name: "xSearch for Safari" }
  - { id: 1573461917, name: "SponsorBlock for YouTube" }
  - { id: 1440147259, name: "AdGuard for Safari" }
  - { id: 1376402589, name: "StopTheMadness" }
  - { id: 462054704, name: "Microsoft Word" }
  - { id: 462058435, name: "Microsoft Excel" }
  - { id: 462062816, name: "Microsoft Powerpoint" }
  - { id: 975937182, name: "Fantastical - Calendar" }
  - { id: 470158793, name: "Keka" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 803453959, name: "Slack for Desktop" }
  - { id: 904280696, name: "Things 3" }
  - { id: 1614730313, name: "MusicBox: Save Music for Later" }
  - { id: 1596506190, name: "Play: Save Videos Watch Later" }
  - { id: 1440405750, name: "MusicHarbor: New Music Tracker" }
  - { id: 1512195368, name: "MusicSmart - Liner Notes" }
  - { id: 1529448980, name: "Reeder 5." }
  - { id: 1475387142, name: "Tailscale" }
  - { id: 403504866, name: "PCalc" }
  - { id: 1568924476, name: "Mela - Recipe Manager" }
  - { id: 775737590, name: "iA Writer" } 
