---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: true
configure_asdf: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - News
  - 'App Store'
  - Freeform
dockitems_persist:
  - name: "Arc"
    path: "/Applications/Arc.app/"
    pos: 1
  - name: "Mail"
    path: "/Applications/Mail.app/"
    pos: 2
  - name: "Fantastical"
    path: "/Applications/Fantastical.app/"
    pos: 3
  - name: "Todoist"
    path: "/Applications/Todoist.app/"
    pos: 4
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 5
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 6
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app/"
    pos: 7
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 9
  - name: "Fork"
    path: "/Applications/Fork.app/"
    pos: 10
  - name: "Music"
    path: "/Applications/Music.app/"
    pos: 11
  - name: "System Settings"
    path: "/Applications/System Settings.app/"
    pos: 12

configure_sudoers: true
sudoers_custom_config: |
  # Enable 'sudo python' to work with an asdf Python install.
  Defaults        env_keep += "ASDF_DATA_DIR"

dotfiles_repo: https://github.com/voboshi/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
dotfiles_files:
  - .zshrc
  - .zshenv
  - .p10k.zsh
  - .gitignore
  - work.gitconfig
  - .osx

homebrew_installed_packages:
  - autoconf
  - automake
  - libtool
  - allure
  - asdf
  - bash
  - bat
  - exa
  - fd
  - findutils
  - fzf
  - gh
  - git-delta
  - helm
  - httpie
  - jq
  - k6
  - kubernetes-cli
  - mas
  - ripgrep
  - shellcheck
  - the_silver_searcher
  - thefuck
  - unzip
  - yq
  - zsh
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - aws/tap/aws-sam-cli
  - cloudquery/tap/cloudquery
  - common-fate/granted/granted
  - hashicorp/tap/terraform-ls
  - kreuzwerker/taps/m1-terraform-provider-helper
  - mergestat/mergestat/mergestat
  - romkatv/powerlevel10k/powerlevel10k
  - turbot/tap/steampipe
  - weaveworks/tap/eksctl
  - wix/brew/applesimutils

homebrew_taps:
  - 1password/tap
  - aws/tap
  - cloudquery/tap
  - common-fate/granted
  - hashicorp/tap
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core
  - kreuzwerker/taps
  - mergestat/mergestat
  - romkatv/powerlevel10k
  - turbot/tap
  - weaveworks/tap
  - wix/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - airfoil
  - android-studio
  - audio-hijack
  - alfred
  - arc
  - bartender
  - downie
  - devonthink
  - fantastical
  - firefox
  - font-fira-code
  - font-fira-code-nerd-font
  - font-iosevka
  - font-iosevka-nerd-font
  - font-iosevka-ss08
  - font-iosevka-ss18
  - fork
  - google-chrome
  - iterm2
  - jetbrains-toolbox
  - keka
  - logi-options-plus
  - lunar
  - macupdater
  - microsoft-word
  - microsoft-excel
  - microsoft-powerpoint
  - microsoft-outlook
  - microsoft-teams
  - onedrive
  - obsidian
  - owasp-zap
  - permute
  - postman
  - soundsource
  - slack
  - todoist
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1568395334, name: "Collections Database" }
  - { id: 775737590, name: "iA Writer" }
  - { id: 403504866, name: "PCalc" }
  - { id: 1224268771, name: "Screens 4" }
  - { id: 1475387142, name: "Tailscale" }
  - { id: 1569813296, name: "1Password for Safari"}
  - { id: 1440147259, name: "AdGuard for Safari" }
  - { id: 1601151613, name: "Baking Soda - Tube Cleaner" }
  - { id: 1606897889, name: "Consent-O-Matic" }
  - { id: 1573461917, name: "SponsorBlock for YouTube" }
  - { id: 1376402589, name: "StopTheMadness" }
  - { id: 1591303229, name: "Vinegar - Tube Cleaner" }
  - { id: 1579902068, name: "xSearch for Safari" }
  - { id: 1614730313, name: "MusicBox: Save Music for Later" }
  - { id: 1596506190, name: "Play: Save Videos Watch Later" }
  - { id: 1440405750, name: "MusicHarbor: New Music Tracker" }
  - { id: 1512195368, name: "MusicSmart - Liner Notes" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409183694, name: "Keynote" }
  - { id: 497799835, name: "Xcode" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
